### ISSUE TITLE
ls19_cdp.sql PARTITION error

### ISSUE THREAD

**Issue by AniFengx** [ZHAMoonlight/referencebook#1]
cdp_user_local 表对应的PARTITION KEY 设置是否有误，如果按原始sql，当导入2千万用户信息数据时，会提示分区键太多，无法插入，个人理解是否应将建表sql改为如下

`
CREATE TABLE cdp_user_local on cluster default(
  unique_user_id UInt64 COMMENT '用户全局唯一ID，ONE-ID',
  name String COMMENT '用户姓名',
  nickname String COMMENT '用户昵称',
  gender Int8 COMMENT '性别：1-男；2-女；3-未知',
  birthday String COMMENT '用户生日：yyyyMMdd',
  user_level Int8 COMMENT '用户等级：1-5',
  register_date DateTime64 COMMENT '注册日期',
  last_login_time DateTime64 COMMENT '最后一次登录时间'
) ENGINE = MergeTree()
    PARTITION BY toYYYYMM(register_date)
    PRIMARY KEY unique_user_id
    ORDER BY unique_user_id;
`

**Comment by ZHAMoonlight** [comment]
已经修改
CREATE TABLE cdp_user_local on cluster default(
  unique_user_id UInt64 COMMENT '用户全局唯一ID，ONE-ID',
  name String COMMENT '用户姓名',
  nickname String COMMENT '用户昵称',
  gender Int8 COMMENT '性别：1-男；2-女；3-未知',
  birthday String COMMENT '用户生日：yyyyMMdd',
  user_level Int8 COMMENT '用户等级：1-5',
  register_date DateTime64 COMMENT '注册日期',
  last_login_time DateTime64 COMMENT '最后一次登录时间'
) ENGINE = MergeTree()
    PARTITION BY toYYYYMMDD(register_date)
    PRIMARY KEY unique_user_id
    ORDER BY unique_user_id;
